// packages/solid/src/index.ts
import { onCleanup, onMount } from 'solid-js';
import UltraTyped from 'ultratyped';

export interface UltraTypedOptions {
  strings: string[];
  typeSpeed?: number;
  backSpeed?: number;
  backDelay?: number;
  loop?: boolean;
}

export function createUltraTyped(el: HTMLElement, options: UltraTypedOptions) {
  let instance: ReturnType<typeof UltraTyped> | null = null;

  onMount(() => {
    instance = UltraTyped(el, options);
  });

  onCleanup(() => {
    instance?.stop();
  });

  return el;
}

// packages/react/src/index.ts
import { useEffect, useRef } from "react";
import UltraTyped from "ultratyped";
import type { UltraTypedOptions } from "ultratyped";

export function useUltraTyped(options: UltraTypedOptions) {
  const ref = useRef<HTMLElement>(null);

  useEffect(() => {
    if (!ref.current) return;
    const instance = UltraTyped(ref.current, options);
    return () => instance.stop();
  }, []);

  return ref;
}
